# ── Supply Chain Backend — Alembic env.py ─────────────────────────────────────
# Generated by: alembic init alembic
# Modified to use SQLAlchemy 2.x sync engine

from logging.config import fileConfig

from sqlalchemy import engine_from_config, pool

from alembic import context

# Import all models so they're registered with Base.metadata
from app.database import Base
import app.models.shipment     # noqa
import app.models.weather      # noqa
import app.models.disruption   # noqa

# Alembic Config object
config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata


def get_url():
    from app.config import get_settings
    return get_settings().DATABASE_URL


def run_migrations_offline() -> None:
    """Run migrations without a DB connection (generates SQL script)."""
    url = get_url()
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Run migrations against a live DB connection."""
    configuration = config.get_section(config.config_ini_section)
    configuration["sqlalchemy.url"] = get_url()
    connectable = engine_from_config(
        configuration,
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    with connectable.connect() as connection:
        context.configure(connection=connection, target_metadata=target_metadata)
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
